### PR TITLE
Change indent/unindent shortcut

### PR DESCRIPTION
**Pull request by bjones1**
...per #66. Also, merge in the setup-fix branch.

### CODE REVIEW

**Comment by andreikop** [comment]
Thanks!
Are we ready to release the version?

**Comment by bjones1** [comment]
Yes, do you want to bump the version or stay with v3.1? I can release now at 3.1 as soon as my builds finish.

**Comment by bjones1** [comment]
I went ahead and released as is. @SergeySatskiy, pip install away!

**Comment by SergeySatskiy** [comment]
Thank you @andreikop , thank you @bjones1 !
pip install worked just fine for me.

**Pull request merged**
