### PR TITLE
python 3.10 compatibility: fix another float-to-int conversion

### PR DESCRIPTION
**Pull request by richboss**
(and also change the gutter color to be less jarring)

### CODE REVIEW

**Comment by andreikop** [comment]
Hi
Why did you change the color?
It was supposed to signal, that the line is wrapped

**Comment by richboss** [comment]
Hi Andrei,

I replied via email 10 days ago. Maybe my message got lost in the spam filter.

> Why did you change the color?

Good question. I always disliked the stark green color as an indicator of line wrap and thought it should be way more subtle. But probably it was not a good idea to confound the color change (a matter of taste) with a legitimate bugfix.

I can make another pull request for the bugfix without the color change, if you want. Perhaps you can make the color configurable, or overwritable in code?

Regards,
Richard

**Comment by andreikop** [comment]
Hi Richard.
Ok, merging as is

**Comment by richboss** [comment]
Hi Andrei,

> Why did you change the color?

good question. I always disliked the stark green color as an indicator of
line wrap and thought it should be way more subtle. But it certainly wasn't
a good idea to confound the color change (a matter of taste) with a
legitimate bugfix.

I can make another pull request for the bugfix without the color change, if
you want. Perhaps you can make the color configurable, or overwritable in
code?

Regards,
Richard

Am Mo., 11. Apr. 2022 um 08:29 Uhr schrieb Andrei Kopats <
***@***.***>:

**Pull request merged**
